-- Add positioning JSONB column to offers table
-- This stores the complete positioning canvas generated by /new-offer

-- Add the column
ALTER TABLE offers 
ADD COLUMN IF NOT EXISTS positioning JSONB;

-- Add comment explaining structure
COMMENT ON COLUMN offers.positioning IS 
'Complete positioning canvas stored as JSON with structure:
{
  "category": {
    "name": "AI Sales Coach",
    "competing_with": "Sales Training Platforms", 
    "differentiator": "Real-time AI practice vs recorded videos"
  },
  "problem": {
    "core_problem": "New sales reps take 6+ months to hit quota",
    "who_feels_it": ["VP Sales", "Sales Managers"],
    "business_impact": "Longer ramp time, missed revenue",
    "customer_language": "Our reps aren''t ready for live calls",
    "awareness_level": "pain_point"
  },
  "symptoms": [
    {
      "type": "hiring",
      "signal": "Posting SDR/BDR jobs",
      "detection": "TheirStack",
      "filter": "last_30_days",
      "reasoning": "Growing teams need training"
    }
  ],
  "outcomes": {
    "immediate": "Reps practice without manager time",
    "short_term": "Cut ramp time 50%",
    "long_term": "$150K+ revenue per rep faster",
    "emotional": "Confidence before first call"
  },
  "alternatives": [
    {
      "name": "Status quo (shadow senior reps)",
      "cons": "Doesn''t scale, inconsistent"
    }
  ],
  "positioning_statement": "We help B2B SaaS sales teams cut ramp time in half by giving reps unlimited AI practice before real calls.",
  "signal_stacks": [
    {
      "name": "Rapid Scaling Stack",
      "signals": ["Series A/B funding", "Hiring 3+ sales roles", "No enablement person"],
      "story": "Growing fast, training is falling on managers",
      "priority": "high",
      "expected_reply_rate": "15-25%"
    }
  ],
  "disqualifying_signals": [
    "Too small (< 10 employees)",
    "Enterprise (1000+ employees)"
  ]
}';

-- Create an index for querying within the positioning JSON
-- (useful if you want to filter by category, problem type, etc.)
CREATE INDEX IF NOT EXISTS idx_offers_positioning_category 
ON offers USING GIN ((positioning -> 'category'));

CREATE INDEX IF NOT EXISTS idx_offers_positioning_problem 
ON offers USING GIN ((positioning -> 'problem'));

-- Add some example queries you can run

-- Query 1: Find offers targeting specific buyer titles
-- SELECT name, positioning->'problem'->'who_feels_it' as buyers
-- FROM offers 
-- WHERE positioning->'problem'->'who_feels_it' ? 'VP Sales';

-- Query 2: Find offers with high-priority signal stacks
-- SELECT name, 
--        jsonb_array_elements(positioning->'signal_stacks') as stacks
-- FROM offers
-- WHERE positioning->'signal_stacks' @> '[{"priority": "high"}]';

-- Query 3: Find offers in a specific category
-- SELECT name, positioning->'category'->>'name' as category
-- FROM offers
-- WHERE positioning->'category'->>'name' ILIKE '%sales%';

-- Update existing offers to have empty positioning structure
-- (so they don't break queries expecting this structure)
UPDATE offers 
SET positioning = jsonb_build_object(
  'category', jsonb_build_object(),
  'problem', jsonb_build_object(),
  'symptoms', '[]'::jsonb,
  'outcomes', jsonb_build_object(),
  'alternatives', '[]'::jsonb,
  'signal_stacks', '[]'::jsonb,
  'disqualifying_signals', '[]'::jsonb
)
WHERE positioning IS NULL;

